### PR TITLE
Pass the endianness to all writing locations

### LINKED ISSUE #41: Cross-endian pcapng writing is incorrect
I'm using pcapng to create test inputs for another system, and I tried to write a big-endian pcapng to make sure that big-endian files are handled correctly. I discovered that the block type and block length are written with native endianness even when the non-native endianness is requested by setting the endianness on the section header block.

I will try to find some time to put together a PR fixing this.

### PR DESCRIPTION
**Pull request by gmacon**
Fixes #41

### CODE REVIEW

**Comment by rshk** [comment]
Change looks good, waiting for CI to pass.
Thanks for taking the time to fix this!

**Comment by gmacon** [comment]
The build failure looks like a manifestation of https://github.com/psf/black/issues/2964. Do you have a preference for upgrading Black or pinning Click in pre-commit?

**Comment by rshk** [comment]
I think upgrading Black would be the best way going forward, so we aren't stuck with an old version?
Thanks for taking time to look into this btw.

**Comment by gmacon** [comment]
OK, here you go.

**Pull request merged**
