### PR TITLE
Final cleanups before version 2 can be released.

### PR DESCRIPTION
**Pull request by Flameeyes**
This cleans up a bit after `setup.py`, and removes the `six` dependency that is now unneeded.

### CODE REVIEW

**Comment by Flameeyes** [comment]
@rshk I'll leave to you to merge this one, and do the tag/release dance if you have a moment — I think we're in a good place for releasing version 2.0.0, Python 3 only and with write support.

**Comment by Flameeyes** [comment]
https://github.com/Flameeyes/usbmon-tools/tree/pcapngwrite is a practical test case for this one.

**Comment by Flameeyes** [comment]
Hm the failure with Travis CI is because `pytest-pycodestyle` now requires Python 3.6+.

I guess we could remove it from 3.5.

**Comment by Flameeyes** [comment]
@rshk can you please take a look? Or should I just merge this by Tuesday if you don't object? :)

**Comment by rshk** [comment]
Looks good 👍 anything in particular you want me to look at? Happy to to merge otherwise. Is this the last PR before a 2.0 release?

**Comment by Flameeyes** [comment]
> Looks good 👍 anything in particular you want me to look at? Happy to to merge otherwise. Is this the last PR before a 2.0 release?

I think it should be, yes. Adding typing (#32) is probably worth keeping on a follow up release, so that users can keep this version until.they fix up their callsites.

Would you like to do the honours for a release? 😄

**Pull request merged**
